openapi: 3.1.0
info:
  title: API сервер для демо-проекта «Шесть городов».
  description: |
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0

tags:
  - name: Offers
    description: Действия с объявлениями.
  - name: Comments
    description: Действия с комментариями.
  - name: Users
    description: Действия с пользователем.
  - name: Favorites
    description: Действия с избранным.
  - name: Categories
    description: Действия с категориями.

servers:
  - url: /api
    description: Development server

components:
  securitySchemes:
    TokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CityName:
      type: string
      enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
    
    PropertyType:
      type: string
      enum: [apartment, house, room, hotel]
      
    Amenities:
      type: string
      enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]

    Coordinates:
      type: object
      additionalProperties: false
      required: [latitude, longitude]
      properties:
        latitude:
          type: number
        longitude:
          type: number

    UserResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        avatarUrl:
          type: string
        type:
          type: string
          enum: [обычный, pro]

    LoginUserDto:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    CreateUserDto:
      type: object
      required: [email, name, password, type]
      properties:
        email:
          type: string
          format: email
        name:
          type: string
          minLength: 1
          maxLength: 15
        password:
          type: string
          minLength: 6
          maxLength: 12
        type:
          type: string
          enum: [обычный, pro]
        avatarUrl:
          type: string
          description: Ссылка на аватар (если файл уже загружен)

    CreateOfferDto:
      type: object
      required: [title, description, city, previewImage, images, isPremium, type, bedrooms, maxAdults, price, goods, coordinates]
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        city:
          $ref: '#/components/schemas/CityName'
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
          minItems: 6
          maxItems: 6
        isPremium:
          type: boolean
        type:
          $ref: '#/components/schemas/PropertyType'
        bedrooms:
          type: integer
          minimum: 1
          maximum: 8
        maxAdults:
          type: integer
          minimum: 1
          maximum: 10
        price:
          type: integer
          minimum: 100
          maximum: 100000
        goods:
          type: array
          items:
            $ref: '#/components/schemas/Amenities'
        coordinates:
          $ref: '#/components/schemas/Coordinates'
    
    UpdateOfferDto:
      type: object
      description: Частичное обновление полей
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 100
        price:
          type: integer
          minimum: 100
          maximum: 100000
        description:
          type: string
          minLength: 20
          maxLength: 1024

    OfferResponse:
      allOf:
        - $ref: '#/components/schemas/CreateOfferDto'
        - type: object
          properties:
            id:
              type: string
            postDate:
              type: string
              format: date-time
            rating: 
              type: number
            commentsCount:
              type: integer
            host:
               $ref: '#/components/schemas/UserResponse'
            isFavorite:
              type: boolean

    OfferShort:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        postDate:
          type: string
          format: date-time
        city:
          $ref: '#/components/schemas/CityName'
        previewImage:
          type: string
        isPremium:
          type: boolean
        rating:
          type: number
        type:
          $ref: '#/components/schemas/PropertyType'
        price:
          type: integer
        commentsCount:
          type: integer
        isFavorite:
          type: boolean

    CreateCommentDto:
      type: object
      required: [offerId, text, rating]
      properties:
        offerId:
          type: string
        text:
          type: string
          minLength: 5
          maxLength: 1024
        rating:
          type: integer
          minimum: 1
          maximum: 5

    CommentResponse:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        rating:
          type: integer
        postDate:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/UserResponse'

paths:
  /users/register:
    post:
      summary: Регистрация нового пользователя
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '409':
          description: Пользователь с таким email уже существует

  /users/login:
    post:
      summary: Вход в приложение
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserDto'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Неверный логин или пароль
    get:
      summary: Проверка состояния пользователя
      tags: [Auth]
      security:
        - TokenAuth: []
      responses:
        '200':
          description: Пользователь авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Пользователь не авторизован
    delete:
      summary: Выход из приложения
      tags: [Auth]
      security:
        - TokenAuth: []
      responses:
        '204':
          description: Сеанс завершен (для сессионной куки)

  /users/{userId}/avatar:
    post:
      summary: Загрузка аватара пользователя
      tags: [Auth]
      security:
        - TokenAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        '201':
          description: Аватар успешно загружен

  /offers:
    get:
      summary: Список предложений
      tags: [Offers]
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 60
            maximum: 60
      responses:
        '200':
          description: Список предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferShort'
    post:
      summary: Создать предложение
      tags: [Offers]
      security:
        - TokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOfferDto'
      responses:
        '201':
          description: Предложение создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'

  /offers/{offerId}:
    parameters:
      - name: offerId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Детальная информация о предложении
      tags: [Offers]
      security:
        - TokenAuth: [] 
      responses:
        '200':
          description: Детальная информация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'
        '404':
          description: Предложение не найдено
    patch:
      summary: Редактировать предложение
      tags: [Offers]
      security:
        - TokenAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOfferDto'
      responses:
        '200':
          description: Предложение обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'
        '403':
          description: Нет прав на редактирование
    delete:
      summary: Удалить предложение
      tags: [Offers]
      security:
        - TokenAuth: []
      responses:
        '204':
          description: Предложение удалено
        '403':
          description: Нет прав на удаление

  /offers/premium/{city}:
    get:
      summary: Премиальные предложения для города
      tags: [Offers]
      parameters:
        - name: city
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/CityName'
      responses:
        '200':
          description: Список премиальных предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferShort'

  /favorites:
    get:
      summary: Список избранных предложений
      tags: [Favorites]
      security:
        - TokenAuth: []
      responses:
        '200':
          description: Список избранного
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferShort'

  /favorites/{offerId}/{status}:
    post:
      summary: Изменить статус избранного
      description: status 1 - добавить, 0 - удалить
      tags: [Favorites]
      security:
        - TokenAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: path
          required: true
          schema:
            type: integer
            enum: [0, 1]
      responses:
        '200':
          description: Статус избранного обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'

  /comments:
    post:
      summary: Добавить комментарий
      tags: [Comments]
      security:
        - TokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentDto'
      responses:
        '201':
          description: Комментарий добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentResponse'

  /comments/{offerId}:
    get:
      summary: Получить список комментариев
      tags: [Comments]
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список комментариев
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentResponse'